name: Deploy Serverless API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Deploy CloudFormation Stack
      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file template.yml \
            --stack-name ServerlessAPIStack \
            --capabilities CAPABILITY_NAMED_IAM CAPABILITY_IAM

      # Optional Step 4: Get CloudFormation Stack Outputs
      - name: Display CloudFormation Stack Outputs
        run: |
          aws cloudformation describe-stacks \
            --stack-name ServerlessAPIStack \
            --query "Stacks[0].Outputs"
